### ISSUE TITLE
unreadable mifare classic

### ISSUE THREAD

**Issue by zoz123** [ikarus23/MifareClassicTool#115]
Hi,
I hope I am in the right place. I don't think it's a bug. It's more a support request...
I am using a nexus 7 (2012 model).
To access my building, I have a mifare classic pass. I tried reading this pass with MCT but it just says "no valid key found in chosen key file" (I selected both std.keys and extended-std.keys files).

Then I tried to read it with taginfo and mifarecard nfc read write applications from play store.
both can get the uid of the pass but none can read the content.

My understanding is that uid is stored on sector 0 but it seems empty...

I attached screenshots. Am I missing something?

![mct_novalidkeyfoundinchosenkeyfile](https://cloud.githubusercontent.com/assets/24525962/23218324/479628b0-f91c-11e6-95e6-98cce331a8ce.png)

![screen_nxptaginfo1](https://cloud.githubusercontent.com/assets/24525962/23218332/49b53636-f91c-11e6-90c9-62ad92fb6d4d.png)

![screen_mifarecardnfcreadwrite](https://cloud.githubusercontent.com/assets/24525962/23218336/4cb6767e-f91c-11e6-952a-a0f7f8e4ac79.png)

**Comment by ikarus23** [comment]
MIFARE Classic uses keys (two per sector) for authentication. Depending on the access conditions you can only read data with the correct keys. Think of it as passwords. If the correct password is not in the key file you cant read the card.

Maybe you have a look at the [General Infromation](https://github.com/ikarus23/MifareClassicTool#general-information) and the [Getting Started](https://github.com/ikarus23/MifareClassicTool#getting-started) section.

**Comment by zoz123** [comment]
I thought that was not valid for sector 0. I assumed sector 0 was public since I understood it contained the uid.

I will order a nfc reader like acr122u and see if I can understand how it works.
thank you for you help.

**Comment by ikarus23** [comment]
In most cases a sector contains 4 blocks. The first block of sector 0 (aka block 0) does indeed contain (among other information) the UID. However, you still can read this block only with a valid key. The fact that you can see the UID even though you don't have the key for block 0 is because the UID is no secret and can be requested according to the ISO 14443-3. I suggest you have a look at the [MIFARE Classic 1k Datasheet](http://www.nxp.com/documents/data_sheet/MF1S50YYX.pdf). It has all the information about the memory layout, the authentication, etc.

**Comment by zoz123** [comment]
I should stop guessing and RTFM now.
Thank you for your explanation.
