### ISSUE TITLE
Emulate Mifare card

### ISSUE THREAD

**Issue by and7ey** [ikarus23/MifareClassicTool#156]
There is NFC Card Emulator app, which is able to emulate NFC cards on Android. For Mifare cards it emulates card id. Is it possible to add the same feature to your app?
Can android phone emulate card data in addition to card id?

**Comment by ikarus23** [comment]
Hi @and7ey, I've noticed this app too. However, I don't think I will add a feature like this. In order to emulate the UID ugly hacks are needed which work only on some Android devices and require root privileges. I think the app using [this technique mentioned on stackoverflow](https://stackoverflow.com/a/28720342). However, on my Nexus 7 (2012) for example, the app does not work.

As far as I know, emulating more than the UID (the rest of the MIFARE Classic data) is even more complex. In theory it should be possible for most devices, but a custom build of the libnfc will be needed.
