### ISSUE TITLE
Mifare Incre./Decr. Value block

### ISSUE THREAD

**Issue by cosmocain** [ikarus23/MifareClassicTool#182]
@ikarus23 

Dear ,

Good afternoon, I would like to ask for your help regarding the option Incr./Decr. Value Block, when trying to write a value in block 8 does it without problems but
when consulting the process done, the option to read label shows me that the result in the blocks is different.
Could you please guide me? attached image capture
![647e46d8-af8f-4edc-beed-2310778da235](https://user-images.githubusercontent.com/38865946/39444763-322ec456-4c8f-11e8-928f-e48f3882d373.jpg)

**Comment by ikarus23** [comment]
Hi! Your screenshot shows two values blocks. Nothing wrong with that. Both are in sector 8 but they are different value blocks. (Remember, a typical sector has 4 blocks.) What are you trying to accomplish? Do you want the same value in both blocks?

**Comment by ikarus23** [comment]
Great to hear that your issues are resolved. However, I can't quite understand the rest you are saying. In your video you successfully changed block 0 of magic card that is compatible with Android.

If you are wondering why you get the error: MCT writes block 0 first. As this will change the UID the card reboots. Since this will cause a connection errors the rest of the tag will not be written correctly. Have a look at https://github.com/ikarus23/MifareClassicTool/issues/122. There are cards that does not have this issue. But for cards like yours I recommend using the "Write Dump" (without block 0 writing) to copy the tag and then use the "Write Block" function to only write block 0.

**Comment by cosmocain** [comment]
Dear ,

I would like to thank you for your delivered feedback.
But how can I know or interpret what is in sector 4 and sector 9?
I do not know how to transform those blocks whether dates or numbers
but I need if you have a web or something similar where you can decode
the mentioned thing.

thank you very much
![imagen1 sector 4](https://user-images.githubusercontent.com/38865946/39523257-51566c1e-4deb-11e8-8825-0663fc730387.png)
![imagen2 sector 9](https://user-images.githubusercontent.com/38865946/39523258-517625cc-4deb-11e8-9b6e-6f09c1be4133.png)

**Comment by cosmocain** [comment]
@ikarus23  Please Help!

**Comment by ikarus23** [comment]
Sorry, but there is no easy way to "convert" the data without knowing what they are. You can write what you want on a Mifare Classic tag. So this data could be anything.

The easiest way to learn about the data is comparing it. Get several cards of what ever you are analyzing. Use the cards and observe what is changing. Look for patterns. e.g. The byte at the end of sector 4 block 0, sector 9 block 1 and sector 11 block 3 looks like a checksum. Do they change if the data in the blocks change? Just look for things like that.
