### ISSUE TITLE
Sector 9 is missing on the source card. Is it problem?

### ISSUE THREAD

**Issue by iceman-1820** [ikarus23/MifareClassicTool#250]
First of all, I would like to thank you for this great app!
I would also like to ask you for advice. I create a card clone. Everything goes fine. Also sector 0 is overwritten.
However, in the source card missing sector 9. I have several source cards available for cloning, and in all cards sector 9 missing.
I'd like to ask what that means? Is in sector 9 somehow encrypted on these cards and is there any important information for work hidden in it? 
I think it is a protection how to recognize a cloned card maybe.

**Comment by ikarus23** [comment]
Yes, each sector (or to be more specific each block) can be protected by keys. MCT comes with a lot of default keys, but if your tags use secret key and appropriate access bits for sector 9 you can't read it. This app can not crack or hack any keys. You need them beforehand. Due to some weaknesses in MIFARE Classic, you can retrieve all the keys (A and B) of a tag with tools like the Proxmark3 or normal RFID-Readers and some special software (mfcuk, mfoc).

Have a look at [the readme](https://github.com/ikarus23/MifareClassicTool#getting-started)
