### ISSUE TITLE
Android app to open door

### ISSUE THREAD

**Issue by JulienRe** [ikarus23/MifareClassicTool#309]
Hello,

Is it possible to clone my badge on my phone, save it on my android phone and open my door with my phone ?

Thank you.

**Comment by longtrung94** [comment]
You can do it, add new card on your locker, enable NFC on your phone, add phone as card. Enjoy it

**Comment by JulienRe** [comment]
> You can do it, add new card on your locker, enable NFC on your phone, add phone as card. Enjoy it
> P/s only work with 13.56mhz card. Make sure screen unlocked alway on when you tab
Thank you for your answer. I wll try it.

**Comment by JulienRe** [comment]
> You can do it, add new card on your locker, enable NFC on your phone, add phone as card. Enjoy it
> P/s only work with 13.56mhz card. Make sure screen unlocked alway on when you tab

Can you write here the application needed to do that please ? Thank you.

**Comment by longtrung94** [comment]
I dont need any app, just on NFC

**Comment by JulienRe** [comment]
With MiFare Classic Tool, I have "READ TAG" of my Vigik door Badge and I have saved it (TagDump.mct). How to open my door with my Phone ? What I need to do after ?

**Comment by JulienRe** [comment]
Can we speak on Discord ? https://discord.gg/8zH3yC

**Comment by longtrung94** [comment]
Can you add new door tag? When you add new tag, use your phone as new tag (enable NFC, phone's screen is on)
I am using my phone as member card at work

**Comment by JulienRe** [comment]
Ahhhh okay I see. Thank you.

**Comment by ikarus23** [comment]
Well this sounds like it is not related to MCT. It sounds like you are talking about a specific product. Since it seams everything is cleared up, I will close this issue for now.

On a side note: No, you can not simulate/emulate a MIFARE Classic card with your phone. At least not on a unrooted and unpatched phone.

Out of curiosity: What do you mean by "add phone as card"? How do you do that with an original Android and no extra app? I never saw such a function

**Comment by JulienRe** [comment]
I think it is not possible to open a Door with phone.
