### ISSUE TITLE
invalid acces conditions or dead sector

### ISSUE THREAD

**Issue by dawaman** [ikarus23/MifareClassicTool#378]
Hello

When I copy RFID tag I have this below error.

![Screenshot_20220318_111204_de syss MifareClassicTool](https://user-images.githubusercontent.com/63778336/158985067-4919e218-2f2e-47c6-a838-e69d0e60adba.jpg)

I have a dump. I write tag with theses options:
Clone
with option seleted:
Uses theses access  conditions for all sectors
Advanced: Enable writing to manufacturer block

Do you know why I have this error?

**Comment by ikarus23** [comment]
You have this error because of the reason right there in the error message: "Key with write access (B) not known." MIFARE Classic tags have two keys per sector (key A and B). Every sector has access conditions (access rights). A common configuration is "reading with key A, writing with key B". It seems like you have key A and were able to read the tag. But it seems like do not have key B to write the tag.

If you are willing to post the dump here, I can have a closer look.

**Comment by dawaman** [comment]
Thanks for your reply. 

Please find my dump.
[UID_651284EC_2020-10-18_12-25-28.zip](https://github.com/ikarus23/MifareClassicTool/files/8378698/UID_651284EC_2020-10-18_12-25-28.zip)

**Comment by dawaman** [comment]
below, the dump from the tag
![Screenshot_20220330_132656_de syss MifareClassicTool](https://user-images.githubusercontent.com/63778336/160824324-474a3051-1dfa-42bd-8f68-258cc247f587.jpg)

**Comment by dawaman** [comment]
thanks for your reply.

Is it possible to retrieve the key B?

**Comment by ikarus23** [comment]
Yes, in most cases this is possible. Due to some weaknesses in MIFARE Classic, you can retrieve all the keys (A and B) of a tag with tools like the [Proxmark3](http://www.proxmark.org/) or normal RFID-Readers and some special software ([mfcuk](https://github.com/nfc-tools/mfcuk), [mfoc](https://github.com/nfc-tools/mfoc)).
