### ISSUE TITLE
Add light theme

### ISSUE THREAD

**Issue by xmha97** [ikarus23/MifareClassicTool#395]
Please add the light theme.

**Comment by ikarus23** [comment]
NEVER! Hacking must be done always in dark mode. :D

All joking aside, providing a proper light and dark theme depending on the system settings seems the right thing to have. But I'm not strong when it comes to UX. Also, to be fair, not very motivated. Maybe someone is willing to have closer look and provide a PR.

**Comment by karageee** [comment]
light mode is cursed

**Comment by ikarus23** [comment]
To follow the system settings, it is basically enough to set the `styles.xml` to:
```
<resources>
    <style name="AppTheme" parent="Theme.AppCompat.DayNight" />
</resources>
```
However, there are still some fixes needed. The "blue" color of MCT should be the themes accent color. And some text (e.g. HexToAscii tool) do not follow the color scheme for some reason...

**Comment by ikarus23** [comment]
Uff, I just wanted to quickly add this feature since using AppCompat provides a light and dark theme.

It had been hours and days of work! I had to learn so much about Androids theme system. Also, I needed to fix a lot of theme related bugs and had to test this on multiple versions. Even back to Android 4.4.

The light theme does not look great. The color palette is still optimized for the dark theme, but I will stop here for now. This "simple" feature took way too many of my resources. :)

Choosing themes is possible as of 075456993c9299c474ad11bcd07f2315fda13184 and will be part of the next release
