### ISSUE TITLE
Include in NetHunter Store

### ISSUE THREAD

**Issue by yesimxev** [ikarus23/MifareClassicTool#423]
Thank you for your awesome work! If you don't mind, we'd like to add this app to the NetHunter Store. Please let me know if there are any concerns 🙏

**Comment by ikarus23** [comment]
Hi. Thank you for asking. You are welcome to put it there. Just use material provided in https://github.com/ikarus23/MifareClassicTool/tree/master/metadata/en-US.  Please add a disclaimer, that it is maintained by a "third party". Otherwise people might think I'm responsible for keeping it up to date. (The person maintaining the Huawaii Store seem to miss some updates :) https://appgallery.huawei.com/#/app/C101783071). I have no experience with the NetHunter store, but if there is an automated way, like the F-Droid store, I would prefer this.
