### ISSUE TITLE
7 byte uid card needed

### ISSUE THREAD

**Issue by ffallah** [ikarus23/MifareClassicTool#511]
Hi Guys,

I need a 7 byte UID changable MiFare Classic 1k which can be programmed with MCT.
I have found a few on aliexpress, but I am not sure if they work with MCT or need a special programmer.
Do you know any specific product that works ?

**Comment by ikarus23** [comment]
Hi. Sorry, it has been several years since I last bought 7 byte MIFARE Classic Gen2/CUID cards on aliexpress. They worked just fine. But after having a quick look I can not find them anymore.

I know these work reliable, but they are very expensive:
* https://lab401.com/en-de/collections/rfid-badges-hf/products/mifare-classic-compatible-1k-7-byte-direct-write-uid
* https://lab401.com/en-de/collections/rfid-badges-hf/products/mifare-classic-compatible-4k-7-byte-uid-modifiable-by-directwrite

**Comment by ikarus23** [comment]
Oh, another tip: head over to the RFID Hacking Discord server at https://discord.com/invite/QfPvGFRQxH. There is a channel for shopping questions. Maybe someone over there knows of a good source for gen2/cuid 7 byte UID tags.
